### ISSUE TITLE
About mlproject.eeg-info

### ISSUE THREAD

**Issue by Aniruddha120** [krishnaik06/mlproject#1]
Hello Krish, hope you are doing well. 
I just followed your tutorial and tried to implement the code along with you. But I have faced some issue regarding 
`pip install -r requirements.txt`

When you ran that, in your editor a file name mlproject.eeg-info appeared. But when I ran that, (after correcting the spelling mistake) no files created! and a bug is showing. That is in the last two lines of setup.py it is saying that syntex error. I am looking for your suggestions. Even I copied your code and still no improvement.

![image](https://user-images.githubusercontent.com/34673269/224372180-0b4e937d-407d-4bd8-b382-aeeb10e07264.png)
![image](https://user-images.githubusercontent.com/34673269/224372483-12ad864f-f5c6-43d7-a83c-af3157790e00.png)

**Comment by Ammar-Raneez** [comment]
You are missing a comma after `author_email`...

**Comment by Aniruddha120** [comment]
> You are missing a comma after `author_email`...

Hey, thanks ! it worked.
